application:
  appName: dwws-pizzaria

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: laylamscouto@gmail.com
    password: fpkxhuxqvisdxcrs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  application:
    name: dwss-pizzaria
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    hikari:
      poolName: Hikari
      auto-commit: false
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    #        database-platform: io.github.jhipster.domain.util.FixedPostgreSQL95Dialect
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    change-log: classpath:/db/master.xml
  #       drop-first: true
  server:
    port: 8080

# ===== NOVAS CONFIGURAÇÕES JWT =====
jwt:
  secret-key: "3o4nKY6gqP7v2M9DZ20Vtd91t3SM0Y9jcpOBgIX7gyo=" # Exemplo: "f5e7a6d8c9b0a1f2e3d4c5b6a7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6"
  expiration: 86400000 # 24 horas em milissegundos
  refresh-expiration: 604800000 # 7 dias em milissegundos

# Configuração de segurança adicional (opcional)
security:
  allowed-origins: "http://localhost:4200" # Frontend Angular
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  expose-headers: "Authorization"
